apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: xihe-statistics-secret
  namespace: xihe-test-v2
spec:
  keysMap:
    config_path:
      key: xihe_statistics_config_path
      path: secrets/data/mindspore/xihe-test-v2
    config_yaml:
      key: xihe_statistics_config_yaml
      path: secrets/data/mindspore/xihe-test-v2
    GITLAB_ENDPOINT:
      key: GITLAB_ENDPOINT
      path: secrets/data/mindspore/xihe-test-v2
    GITLAB_GRAPHQL_ENDPOINT:
      key: GITLAB_GRAPHQL_ENDPOINT
      path: secrets/data/mindspore/xihe-test-v2
    GITLAB_TOKEN:
      key: GITLAB_TOKEN
      path: secrets/data/mindspore/xihe-test-v2
  name: xihe-statistics-secret
