---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mindspore-xihe-docs-tls
  namespace: xihe-docs
spec:
  name: mindspore-xihe-docs-tls
  keysMap:
    ca.crt:
      path: secrets/data/mindspore/xihe-docs
      key: server.crt
    tls.crt:
      path: secrets/data/mindspore/xihe-docs
      key: server.crt
    tls.key:
      path: secrets/data/mindspore/xihe-docs
      key: server.key
