apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    domain:
      min_finetune_name_length: 1
      max_finetune_name_length: 64
      finetunes:
        opt-caption:
          tasks:
          - finetune
          hyperparameters:
          - epochs
          - start_learning_rate
          - end_learning_rate

    finetune:
      endpoint: http://big-model-finetune.xihe-new.svc.cluster.local
      username: "${FINETUNE_USERNAME}"
      password: "${FINETUNE_PASSWORD}"

    watch:
      endpoint: service-internal-server.xihe-new.svc.cluster.local:8000
      max_watch_num: 10
