apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-secret
  namespace: mindspore-doc-search
spec:
  keysMap:
    depp:
      key: depp
      path: secrets/data/mindspore/doc-search
    eshost:
      key: eshost
      path: secrets/data/mindspore/doc-search
    espassword:
      key: espassword
      path: secrets/data/mindspore/doc-search
    esusername:
      key: esusername
      path: secrets/data/mindspore/doc-search
    searchsystem:
      key: searchsystem
      path: secrets/data/mindspore/doc-search
    GIT_USERNAME:
      key: GIT_USERNAME
      path: secrets/data/mindspore/doc-search
    GIT_PASSWORD:
      key: GIT_PASSWORD
      path: secrets/data/mindspore/doc-search
    MINDSPORE_OFFICIAL:
      key: MINDSPORE_OFFICIAL
      path: secrets/data/mindspore/doc-search
    xarmor_app_id:
      key: xarmor_app_id
      path: secrets/data/mindspore/rasp_secret
    xarmor_app_token:
      key: xarmor_app_token
      path: secrets/data/mindspore/rasp_secret
    xarmor_backend_url:
      key: xarmor_backend_url
      path: secrets/data/mindspore/rasp_secret
    xarmor_tenant_id:
      key: xarmor_tenant_id
      path: secrets/data/mindspore/rasp_secret
  name: doc-search-secret

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-tls
  namespace: mindspore-doc-search
spec:
  keysMap:
    ca.crt:
      path: secrets/data/mindspore/mindspore-cn-tls
      key: ca.cert
    tls.crt:
      path: secrets/data/mindspore/mindspore-cn-tls
      key: ca.cert
    tls.key:
      path: secrets/data/mindspore/mindspore-cn-tls
      key: ca.key
  name: doc-search-tls
