apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - cann/air
      merge_method: squash
      branch_merge_method:
        master: merge
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."

      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."

      - label: ci-pipeline-passed
        person: turing_project
        tips_if_missing: "Please wait for the CI test to be completed."
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."

    - repos:
      - cann/acl
      - cann/abl-kernel
      - cann/aoe-flow
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."

      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."

      - label: ci-pipeline-passed
        person: turing_project
        tips_if_missing: "Please wait for the CI test to be completed."
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."
