apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: mindspore-usercenter
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: website
  type: ClusterIP
