apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: secret
spec:
  name: secret-sync-agent
  keysMap:
    gitee-token:
      path: secrets/data/mindspore/robot-gitee
      key: robot-openeuler-token
    github-token:
       path: secrets/data/mindspore/robot-github
       key: robot-openeuler-token
    
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: secret-tls
spec:
  name: secret-tls-sync-agent
  keysMap:
    ca.crt:
      path: secrets/data/mindspore/robot-github
      key: server.crt
    tls.crt:
      path: secrets/data/mindspore/robot-github
      key: server.crt
    tls.key:
      path: secrets/data/mindspore/robot-github
      key: server.key