apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secrets.yaml
- scavenger
- cla
- label
- tide
- lifecycle
- assign
- checkpr
- review-trigger
- review-trigger-new
- hook-dispatcher
- hook-delivery
- access
- test
commonLabels:
  app: infrastructure-robot-gitee
commonAnnotations:
  email: chenzeng765@163.com
  owner: chenzeng
namespace: robot-gitee-mindspore
